# Site settings
title: JRowing
name: Joe Rowing # your name
email: joe@jrowing.com # your email address
description: All views my own. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jrowing.com" # the base hostname & protocol for your site
twitter_username: jrowing # your Twitter username
github_username: jrowing # your Github username
disqus_username: jrowing # your disqus username

google-analytics:  # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
